- name: Mr Provisioner Example
  hosts: localhost
  gather_facts: false
  vars:
    mr_provisioner_url: http://172.27.80.1:5000
    mr_provisioner_arch: 'arm64'
    mr_provisioner_subarch: 'efi'
    mr_provisioner_preseed_name: 'danrue/debian-mini-install-20180413'
    mr_provisioner_preseed_path: './preseeds/debian-mini-install-20180413'
    mr_provisioner_preseed_public: false
    mr_provisioner_machine_name: 'j12-m1-c34n1'

    erp_debian_installer_environment: stable # alternatively, use 'staging'
    erp_build_number: false # Set to a build number (i.e. 505).
                            # 'false' will discover the latest build.

  roles:
    # Download the latest ERP staging build
    - role: Linaro.erp-get-build
      ansible_become: no

    # Provision the host(s) defined in hosts file
    # with aforementioned build
    - role: Linaro.mr-provisioner
      ansible_become: no

- hosts: mr_provisioner_hosts
  gather_facts: false
  tasks:
    - name: Wait for host for 3600 seconds, but only start checking after 60.
      wait_for_connection:
        delay: 60
        timeout: 3600

- hosts: mr_provisioner_hosts
  gather_facts: false
  tasks:

    # Run some tasks on the provisioned host
    - name: Get uname -a
      command: uname -a
      register: uname
    - name: Print out uname
      debug:
        msg: "{{uname.stdout}}"

    - name: whoami
      command: whoami
      register: whoami
    - name: Print out whoami
      debug:
        msg: "{{whoami.stdout}}"

    - name: Install some packages
      apt:
        update_cache: yes
        cache_valid_time: 86400
        pkg: "{{item}}"
      with_items:
        - git
        - python-pip
        - sysstat
        - strace
        - sl # My personal favorite

